; [pytest]
; testpaths = tests
; python_files = test_*.py
; addopts = -v

# This tells pytest: "The following configuration belongs to pytest."
# Without it, pytest ignores the file.
[pytest]

# Directory where pytest will look for tests
# Instead of scanning the whole project, it will only search inside "tests/"
testpaths = tests

# Pattern for test file names
# pytest will only collect files that match this pattern
# Example: test_math.py, test_api.py
python_files = test_*.py

# -v means verbose mode (shows detailed test results)
addopts = -v